/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

/**
 *
 * @author fgarr
 */
public class AccountSelectionWindow extends javax.swing.JPanel {

    /**
     * Creates new form AccountSelectionWindow
     */
    public AccountSelectionWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imgSecondaryLogo = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnAccount3 = new javax.swing.JButton();
        btnAccount2 = new javax.swing.JButton();
        btnAccount1 = new javax.swing.JButton();
        btnAccount4 = new javax.swing.JButton();
        btnAccount5 = new javax.swing.JButton();
        lblInstructions2 = new javax.swing.JLabel();
        lblInstructions1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 5, true));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgSecondaryLogo.setIcon(new javax.swing.ImageIcon("C:\\Users\\fgarr\\Desktop\\Carpetas\\Nando\\U\\Fidélitas\\III Cuatrimestre\\5. Programación Cliente-Servidor Concurrente\\Proyecto\\Avance #2\\atm-app\\src\\main\\java\\Images\\SecondaryLogo.jpeg")); // NOI18N
        imgSecondaryLogo.setText("jLabel1");
        add(imgSecondaryLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 110));

        btnBack.setBackground(new java.awt.Color(102, 102, 255));
        btnBack.setFont(new java.awt.Font("Franklin Gothic Book", 0, 28)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 830, 200, 70));

        btnAccount3.setBackground(new java.awt.Color(102, 102, 255));
        btnAccount3.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        btnAccount3.setForeground(new java.awt.Color(255, 255, 255));
        btnAccount3.setText("Account 3");
        add(btnAccount3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 460, 460, 70));

        btnAccount2.setBackground(new java.awt.Color(102, 102, 255));
        btnAccount2.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        btnAccount2.setForeground(new java.awt.Color(255, 255, 255));
        btnAccount2.setText("Account 2");
        add(btnAccount2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 460, 70));

        btnAccount1.setBackground(new java.awt.Color(102, 102, 255));
        btnAccount1.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        btnAccount1.setForeground(new java.awt.Color(255, 255, 255));
        btnAccount1.setText("Account 1");
        btnAccount1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccount1ActionPerformed(evt);
            }
        });
        add(btnAccount1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 460, 70));

        btnAccount4.setBackground(new java.awt.Color(102, 102, 255));
        btnAccount4.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        btnAccount4.setForeground(new java.awt.Color(255, 255, 255));
        btnAccount4.setText("Account 4");
        add(btnAccount4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 540, 460, 70));

        btnAccount5.setBackground(new java.awt.Color(102, 102, 255));
        btnAccount5.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        btnAccount5.setForeground(new java.awt.Color(255, 255, 255));
        btnAccount5.setText("Account 5");
        add(btnAccount5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 620, 460, 70));

        lblInstructions2.setFont(new java.awt.Font("Franklin Gothic Book", 0, 36)); // NOI18N
        lblInstructions2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInstructions2.setText("to perform the transaction:");
        lblInstructions2.setToolTipText("");
        add(lblInstructions2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 700, -1));

        lblInstructions1.setFont(new java.awt.Font("Franklin Gothic Book", 0, 36)); // NOI18N
        lblInstructions1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInstructions1.setText("Select the account in wich you wish");
        lblInstructions1.setToolTipText("");
        add(lblInstructions1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 700, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAccount1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccount1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAccount1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccount1;
    private javax.swing.JButton btnAccount2;
    private javax.swing.JButton btnAccount3;
    private javax.swing.JButton btnAccount4;
    private javax.swing.JButton btnAccount5;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel imgSecondaryLogo;
    private javax.swing.JLabel lblInstructions1;
    private javax.swing.JLabel lblInstructions2;
    // End of variables declaration//GEN-END:variables
}
