/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

/**
 *
 * @author fgarr
 */
public class Generic4Window extends javax.swing.JPanel {

    /**
     * Creates new form Generic4Window
     */
    public Generic4Window() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imgSecondaryLogo = new javax.swing.JLabel();
        txtInput = new javax.swing.JTextField();
        btnAction = new javax.swing.JButton();
        lblInstructions = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 5, true));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgSecondaryLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/SecondaryLogo.png"))); // NOI18N
        imgSecondaryLogo.setText("jLabel1");
        add(imgSecondaryLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 130));

        txtInput.setBackground(new java.awt.Color(204, 204, 204));
        txtInput.setFont(new java.awt.Font("Franklin Gothic Book", 0, 36)); // NOI18N
        txtInput.setForeground(new java.awt.Color(153, 153, 153));
        txtInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtInput.setText("TXT");
        txtInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInputActionPerformed(evt);
            }
        });
        add(txtInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 460, 70));

        btnAction.setBackground(new java.awt.Color(102, 102, 255));
        btnAction.setFont(new java.awt.Font("Franklin Gothic Book", 0, 36)); // NOI18N
        btnAction.setForeground(new java.awt.Color(255, 255, 255));
        btnAction.setText("TXT");
        btnAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionActionPerformed(evt);
            }
        });
        add(btnAction, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 460, 460, 70));

        lblInstructions.setFont(new java.awt.Font("Franklin Gothic Book", 0, 36)); // NOI18N
        lblInstructions.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInstructions.setText("TXT");
        add(lblInstructions, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 700, 60));

        btnBack.setBackground(new java.awt.Color(102, 102, 255));
        btnBack.setFont(new java.awt.Font("Franklin Gothic Book", 0, 28)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 830, 200, 70));
    }// </editor-fold>//GEN-END:initComponents

    private void txtInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInputActionPerformed

    private void btnActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAction;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel imgSecondaryLogo;
    private javax.swing.JLabel lblInstructions;
    private javax.swing.JTextField txtInput;
    // End of variables declaration//GEN-END:variables
}
