
package GUI;

import Models.User;


public class MainMenuWindow extends javax.swing.JPanel {
    
    private final ATM actualContainer;
    private final LoginWindow loginWindow;
    private final User user;

    /**
     * Creates new form MainManuWindow
     * @param container
     * @param user
     */
    
    public MainMenuWindow(ATM container, LoginWindow loginWindow, User user) {
        this.actualContainer = container;
        this.loginWindow = loginWindow;
        this.user = user;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMoneyDeposit = new javax.swing.JButton();
        imgSecondaryLogo = new javax.swing.JLabel();
        btnWithdrawal = new javax.swing.JButton();
        btnRequestAccount = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnMakeTransfer = new javax.swing.JButton();
        lblInstructions = new javax.swing.JLabel();
        btnPrintDocuments = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 122, 255), 5, true));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMoneyDeposit.setBackground(new java.awt.Color(102, 102, 255));
        btnMoneyDeposit.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        btnMoneyDeposit.setForeground(new java.awt.Color(255, 255, 255));
        btnMoneyDeposit.setText("Money deposit");
        add(btnMoneyDeposit, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 460, 460, 70));

        imgSecondaryLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MainLogo.png"))); // NOI18N
        imgSecondaryLogo.setLabelFor(imgSecondaryLogo);
        add(imgSecondaryLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 190, 260));

        btnWithdrawal.setBackground(new java.awt.Color(102, 102, 255));
        btnWithdrawal.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        btnWithdrawal.setForeground(new java.awt.Color(255, 255, 255));
        btnWithdrawal.setText("Withdrawal of funds");
        add(btnWithdrawal, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 460, 70));

        btnRequestAccount.setBackground(new java.awt.Color(102, 102, 255));
        btnRequestAccount.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        btnRequestAccount.setForeground(new java.awt.Color(255, 255, 255));
        btnRequestAccount.setText("Request accout");
        btnRequestAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestAccountActionPerformed(evt);
            }
        });
        add(btnRequestAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 460, 70));

        btnExit.setBackground(new java.awt.Color(102, 102, 255));
        btnExit.setFont(new java.awt.Font("Franklin Gothic Book", 0, 28)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 830, 200, 70));

        btnMakeTransfer.setBackground(new java.awt.Color(102, 102, 255));
        btnMakeTransfer.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        btnMakeTransfer.setForeground(new java.awt.Color(255, 255, 255));
        btnMakeTransfer.setText("Make a transfer");
        add(btnMakeTransfer, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 540, 460, 70));

        lblInstructions.setFont(new java.awt.Font("Franklin Gothic Book", 0, 36)); // NOI18N
        lblInstructions.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInstructions.setText("Select an option to proceed:");
        add(lblInstructions, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 700, 60));

        btnPrintDocuments.setBackground(new java.awt.Color(102, 102, 255));
        btnPrintDocuments.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        btnPrintDocuments.setForeground(new java.awt.Color(255, 255, 255));
        btnPrintDocuments.setText("Print documents");
        add(btnPrintDocuments, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 620, 460, 70));
    }// </editor-fold>//GEN-END:initComponents

    private void btnRequestAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestAccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRequestAccountActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        actualContainer.showPanel(loginWindow);
    }//GEN-LAST:event_btnExitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnMakeTransfer;
    private javax.swing.JButton btnMoneyDeposit;
    private javax.swing.JButton btnPrintDocuments;
    private javax.swing.JButton btnRequestAccount;
    private javax.swing.JButton btnWithdrawal;
    public javax.swing.JLabel imgSecondaryLogo;
    private javax.swing.JLabel lblInstructions;
    // End of variables declaration//GEN-END:variables
}
